SimpleNavigation.register_renderer bootstrap_topbar_list: BootstrapTopbarList
SimpleNavigation.register_renderer inspinia_sidebar_renderer: InspiniaSidebarRenderer
SimpleNavigation.register_renderer inspinia_top_nav: InspiniaTopNav
