source 'https://ruby.taobao.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.1'
# Use mysql as the database for Active Record
gem 'mysql2'
# Use Puma as the app server
gem 'puma', '~> 3.0', require: false
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
gem 'thor', '0.19.1'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Navigation
gem 'simple-navigation'

# Grid
gem 'datagrid'

# Pagination
gem 'kaminari'

# User authentication
gem 'devise'
gem 'devise-i18n'

# Form helper
gem 'simple_form'

# Settings
gem 'settingslogic'

# I18n
gem 'rails-i18n'
gem 'i18n-active_record'

# Authentication
gem 'cancancan'

# Parse Excels
gem 'rubyXL'

gem 'nav_lynx'

# Attachments
gem 'paperclip'

gem "breadcrumbs_on_rails"

gem 'rbase', git: 'https://github.com/aya-soft/rbase.git', :require => 'rbase'
gem 'dbf'
gem 'cells'
gem 'rails-dom-testing' #Quick fix for Cells 3 and Rails 4, will be removed after new version of Cells released.

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri

  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  # gem 'quiet_assets'
  gem 'rspec-cells'

  gem 'rspec-rails'
  gem 'autotest-rails'
  gem 'rspec-core'
end

group :test do
  gem 'simplecov', :require => false
end

# Assets related
gem 'bootstrap-sass'
gem 'font-awesome-rails'
gem 'bootstrap3-datetimepicker-rails'
gem 'momentjs-rails'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
