# source 'https://rubygems.org'
source 'http://ruby.taobao.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'
# Use mysql as the database for Active Record
gem 'mysql2'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
gem 'coffee-script-source', '~>1.8.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-ui-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'jquery-turbolinks'
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'simple_form',            '~> 3.1.0'
gem 'simple-navigation',      '~> 3.14.0'
gem 'wice_grid',              '3.4.14'
gem 'nav_lynx'
gem 'rails-i18n'
gem 'i18n-active_record',
      :git => 'https://github.com/svenfuchs/i18n-active_record.git',
      :require => 'i18n/active_record'
gem "breadcrumbs_on_rails"
gem 'devise'
gem 'paperclip'
gem 'kaminari'
gem 'nprogress-rails'
gem 'settingslogic'
gem 'remotipart',               '~> 1.2'
gem 'rbase', git: 'https://github.com/aya-soft/rbase.git', :require => 'rbase'
gem 'dbf'
gem 'cells',                    '3.11.3'
gem 'rails-dom-testing' #Quick fix for Cells 3 and Rails 4, will be removed after new version of Cells released.

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  gem 'quiet_assets'
  gem 'rspec-cells'

  gem 'rspec-rails',    '3.2.1'
  gem 'autotest-rails', '4.2.1'
  gem 'rspec-core',     '3.2.2'
end

group :test do
  gem 'simplecov', :require => false
end

# Assets related
gem 'less-rails-bootstrap', '~> 3.3.2'
gem 'font-awesome-rails', '~> 4.3.0'

gem 'bootstrap3-datetimepicker-rails', '~> 4.0.0'
gem 'momentjs-rails', '~> 2.9.0'
