# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b29189a7d6f7b865572928963f38b92fb53ce40522f34f000002907fc6eea033cde10e5263d85f28a62b1a2c0e3ead5c9cb7047d802ddf00fdf680a776fe5b1

test:
  secret_key_base: 8928204c867246e0bb399bbe6fbfd066c69bbbe57b20dfa1a6f872b8006da63ddf46440701ec1878e564a5398bd53848bf6c8cde77f884f7af51fc623f395e41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
